version: 2.1


jobs:
  build:
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - run: make

  test:
    docker:
      - image: gcc:8.2
    steps:
      - run: make test

workflows:
  build and test:
    jobs:
      - build
      - test
